syntax = "proto3";

package tolo.graph.v1;

import "tolo/kernel/v1/kernel.proto";

service GraphSupplyService {
  rpc GetCurrentRevision(GetCurrentRevisionRequest) returns (tolo.kernel.v1.Graph);
  rpc GetObservationPointMappings(GetMappingsRequest) returns (GetMappingsResponse);
}

message ObservationPointMapping {
  string observation_point_id = 1;
  tolo.kernel.v1.GraphAnchor anchor = 2;
}

message GetCurrentRevisionRequest {
  string event_id = 1;
}

message GetMappingsRequest {
  string event_id = 1;
}

message GetMappingsResponse {
  string revision_id = 1;
  repeated ObservationPointMapping mappings = 2;
}
