// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/edge_device.go
//
// Generated by this command:
//
//	mockgen -source=../repository/edge_device.go -destination=mock_edge_device_repository_test.go -package=application_test
//

// Package application_test is a generated GoMock package.
package application_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/pj-hoakari/tolo-observation/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEdgeDeviceRepository is a mock of EdgeDeviceRepository interface.
type MockEdgeDeviceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEdgeDeviceRepositoryMockRecorder
	isgomock struct{}
}

// MockEdgeDeviceRepositoryMockRecorder is the mock recorder for MockEdgeDeviceRepository.
type MockEdgeDeviceRepositoryMockRecorder struct {
	mock *MockEdgeDeviceRepository
}

// NewMockEdgeDeviceRepository creates a new mock instance.
func NewMockEdgeDeviceRepository(ctrl *gomock.Controller) *MockEdgeDeviceRepository {
	mock := &MockEdgeDeviceRepository{ctrl: ctrl}
	mock.recorder = &MockEdgeDeviceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEdgeDeviceRepository) EXPECT() *MockEdgeDeviceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEdgeDeviceRepository) Create(ctx context.Context, device domain.EdgeDevice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEdgeDeviceRepositoryMockRecorder) Create(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEdgeDeviceRepository)(nil).Create), ctx, device)
}

// FindByID mocks base method.
func (m *MockEdgeDeviceRepository) FindByID(ctx context.Context, id domain.EdgeDeviceID) (domain.EdgeDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.EdgeDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockEdgeDeviceRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockEdgeDeviceRepository)(nil).FindByID), ctx, id)
}

// FindByObservationPointID mocks base method.
func (m *MockEdgeDeviceRepository) FindByObservationPointID(ctx context.Context, id domain.ObservationPointID) (domain.EdgeDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByObservationPointID", ctx, id)
	ret0, _ := ret[0].(domain.EdgeDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByObservationPointID indicates an expected call of FindByObservationPointID.
func (mr *MockEdgeDeviceRepositoryMockRecorder) FindByObservationPointID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByObservationPointID", reflect.TypeOf((*MockEdgeDeviceRepository)(nil).FindByObservationPointID), ctx, id)
}

// ListByEvent mocks base method.
func (m *MockEdgeDeviceRepository) ListByEvent(ctx context.Context, eventID string, includeUnregistered bool) ([]domain.EdgeDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEvent", ctx, eventID, includeUnregistered)
	ret0, _ := ret[0].([]domain.EdgeDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEvent indicates an expected call of ListByEvent.
func (mr *MockEdgeDeviceRepositoryMockRecorder) ListByEvent(ctx, eventID, includeUnregistered any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEvent", reflect.TypeOf((*MockEdgeDeviceRepository)(nil).ListByEvent), ctx, eventID, includeUnregistered)
}

// Save mocks base method.
func (m *MockEdgeDeviceRepository) Save(ctx context.Context, device domain.EdgeDevice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockEdgeDeviceRepositoryMockRecorder) Save(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEdgeDeviceRepository)(nil).Save), ctx, device)
}

// SaveHeartbeat mocks base method.
func (m *MockEdgeDeviceRepository) SaveHeartbeat(ctx context.Context, device domain.EdgeDevice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveHeartbeat", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveHeartbeat indicates an expected call of SaveHeartbeat.
func (mr *MockEdgeDeviceRepositoryMockRecorder) SaveHeartbeat(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveHeartbeat", reflect.TypeOf((*MockEdgeDeviceRepository)(nil).SaveHeartbeat), ctx, device)
}
