// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/greeting.go
//
// Generated by this command:
//
//	mockgen -source=../repository/greeting.go -destination=mock_greeting_repository_test.go -package=application_test
//

// Package application_test is a generated GoMock package.
package application_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/pj-hoakari/tolo-observation/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGreetingRepository is a mock of GreetingRepository interface.
type MockGreetingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGreetingRepositoryMockRecorder
	isgomock struct{}
}

// MockGreetingRepositoryMockRecorder is the mock recorder for MockGreetingRepository.
type MockGreetingRepositoryMockRecorder struct {
	mock *MockGreetingRepository
}

// NewMockGreetingRepository creates a new mock instance.
func NewMockGreetingRepository(ctrl *gomock.Controller) *MockGreetingRepository {
	mock := &MockGreetingRepository{ctrl: ctrl}
	mock.recorder = &MockGreetingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGreetingRepository) EXPECT() *MockGreetingRepositoryMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockGreetingRepository) Record(arg0 context.Context, arg1 domain.Greeting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockGreetingRepositoryMockRecorder) Record(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockGreetingRepository)(nil).Record), arg0, arg1)
}
