// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/measurement.go
//
// Generated by this command:
//
//	mockgen -source=../repository/measurement.go -destination=mock_measurement_repository_test.go -package=application_test
//

// Package application_test is a generated GoMock package.
package application_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/pj-hoakari/tolo-observation/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMeasurementRepository is a mock of MeasurementRepository interface.
type MockMeasurementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMeasurementRepositoryMockRecorder
	isgomock struct{}
}

// MockMeasurementRepositoryMockRecorder is the mock recorder for MockMeasurementRepository.
type MockMeasurementRepositoryMockRecorder struct {
	mock *MockMeasurementRepository
}

// NewMockMeasurementRepository creates a new mock instance.
func NewMockMeasurementRepository(ctrl *gomock.Controller) *MockMeasurementRepository {
	mock := &MockMeasurementRepository{ctrl: ctrl}
	mock.recorder = &MockMeasurementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeasurementRepository) EXPECT() *MockMeasurementRepositoryMockRecorder {
	return m.recorder
}

// RecordAll mocks base method.
func (m *MockMeasurementRepository) RecordAll(ctx context.Context, tenantPublicID, eventID string, measurements []domain.Measurement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAll", ctx, tenantPublicID, eventID, measurements)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordAll indicates an expected call of RecordAll.
func (mr *MockMeasurementRepositoryMockRecorder) RecordAll(ctx, tenantPublicID, eventID, measurements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAll", reflect.TypeOf((*MockMeasurementRepository)(nil).RecordAll), ctx, tenantPublicID, eventID, measurements)
}
